build : compile_and_run
 
compile_and_run :
	g++ main_to_csv.cpp fileManager.cpp cell.cpp AnsiTerminal.cpp new_formula.cpp spreadsheet.cpp DoubleValue.cpp IntValue.cpp FormulaCell.cpp StringValue.cpp ValueCell.cpp -o HBA.out
run :
	./HBA.out